### ISSUE TITLE
Hi, great work can I ask you for a copy of this circuit

### ISSUE THREAD

**Issue by duongnv0499** [txp666/HelloWord-Keyboard-Dynamic#1]
I love the Pengzhui's keyboard, especially this part. I tried to make this but I'm not an engineering guy, so I hope that I can get your contact information (eg email, WeChat ...) to easily ask you (who successfully made it) some questions regard to this project. Thank you for reading, and thank you for your great work.

**Comment by txp666** [comment]
> I love the Pengzhui's keyboard, especially this part. I tried to make this but I'm not an engineering guy, so I hope that I can get your contact information (eg email, WeChat ...) to easily ask you (who successfully made it) some questions regard to this project. Thank you for reading, and thank you for your great work.

771454616@qq.com
